# Generated by Django 3.2 on 2021-05-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_or_number',
            new_name='client_org_number',
        ),
    ]
